<template><div class="h-full overflow-y-auto"><div class="max-w-6xl mx-auto px-4 sm:px-6 py-6 space-y-5">
  <div class="flex items-center justify-between"><h1 class="text-2xl font-bold">📋 Logs</h1><div class="flex gap-3"><button @click="clean" class="text-sm text-red-400">Dọn log cũ</button><button @click="loadFiles" class="text-sm text-indigo-400">↻ Refresh</button></div></div>
  <section class="bg-gray-800 rounded-xl p-4"><div class="flex flex-wrap gap-2"><div v-for="file in files" :key="file.filename" class="flex items-center gap-1"><button @click="open(file.filename)" class="px-3 py-1.5 rounded-lg text-xs font-mono border transition" :class="current===file.filename?'border-indigo-500 text-white':'border-gray-600 text-gray-300'">{{ file.filename }}</button><a :href="downloadUrl(file.filename)" :download="file.filename" class="px-2 py-1.5 text-xs border border-gray-700 rounded">⤓</a><span class="text-[10px] text-gray-500">{{ size(file.sizeBytes) }}</span></div><span v-if="!files.length" class="text-xs text-gray-500">Không có file log nào.</span></div></section>
  <section class="bg-black border border-gray-800 rounded-xl overflow-hidden"><div class="px-4 py-3 border-b border-gray-800 flex flex-wrap items-center gap-3"><strong class="text-sm text-gray-300">{{ current || 'Chọn file log' }}</strong><input v-model="filter" placeholder="Lọc nội dung…" class="ml-auto px-3 py-1.5 bg-gray-900 border border-gray-700 rounded text-xs"/><label class="text-xs text-gray-400"><input v-model="autoScroll" type="checkbox" class="accent-indigo-500"/> Auto-scroll</label></div><pre ref="pre" class="p-4 text-xs leading-5 font-mono whitespace-pre-wrap break-words h-[60vh] overflow-auto"><template v-for="(line,index) in filteredLines" :key="index"><span :class="lineClass(line)">{{ line }}</span>{{ '\n' }}</template></pre></section>
</div></div></template>
<script setup>
import { computed, nextTick, onMounted, ref, watch } from 'vue'; import { API_BASE } from '@/api/request'; import { cleanLogs, getLogContent, getLogs } from '@/api/stats';
const files=ref([]),current=ref(''),raw=ref(''),filter=ref(''),autoScroll=ref(true),pre=ref(null);const filteredLines=computed(()=>raw.value.split('\n').filter(line=>!filter.value||line.toLowerCase().includes(filter.value.toLowerCase())));
const loadFiles=async()=>{files.value=await getLogs()||[];const today=`${new Date().toISOString().slice(0,10)}.log`;if(!current.value&&files.value.some(f=>f.filename===today))await open(today);};const open=async filename=>{current.value=filename;raw.value=await getLogContent(filename);};const downloadUrl=f=>`${API_BASE}/logs/${encodeURIComponent(f)}`;const size=b=>!Number.isFinite(b)?'':b<1024?`${b}B`:b<1048576?`${(b/1024).toFixed(1)}KB`:`${(b/1048576).toFixed(1)}MB`;const lineClass=l=>/\[ERROR\]/.test(l)?'text-red-400':/\[WARN\]/.test(l)?'text-yellow-400':/\[INFO\]/.test(l)?'text-green-400':/\[OpenClaw\]/.test(l)?'text-cyan-400':'text-gray-300';const clean=async()=>{if(confirm('Xóa các log đã hết hạn lưu trữ?')){await cleanLogs();await loadFiles();}};watch([filteredLines,autoScroll],async()=>{if(autoScroll.value){await nextTick();if(pre.value)pre.value.scrollTop=pre.value.scrollHeight;}});onMounted(loadFiles);
</script>
