<template><div class="h-full overflow-y-auto"><div class="max-w-3xl mx-auto px-4 sm:px-6 py-6 space-y-6">
  <div class="flex justify-between"><h1 class="text-2xl font-bold">👥 Users</h1><button @click="load" class="text-sm text-indigo-400">↻ Refresh</button></div>
  <form @submit.prevent="add" class="bg-gray-800 rounded-xl p-6 space-y-4"><h2 class="font-semibold text-gray-300">Thêm user</h2><div class="grid sm:grid-cols-3 gap-3"><input v-model.trim="newUser.username" required placeholder="Username" class="field"/><input v-model="newUser.password" required minlength="6" type="password" placeholder="Password (min 6)" class="field"/><select v-model="newUser.role" class="field"><option value="user">User</option><option value="admin">Admin</option></select></div><button class="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-sm font-semibold">+ Thêm user</button><p v-if="message" :class="ok?'text-green-400':'text-red-400'" class="text-sm">{{ message }}</p></form>
  <section class="bg-gray-800 rounded-xl p-6"><h2 class="font-semibold text-gray-300 mb-4">Danh sách users</h2><p v-if="!users.length" class="text-sm text-gray-500">Chưa có user nào.</p><div v-else class="divide-y divide-gray-700"><article v-for="user in users" :key="user.username" class="flex items-center gap-3 py-3"><div class="w-8 h-8 rounded-full bg-gray-600 flex items-center justify-center text-xs font-bold">{{ user.username?.charAt(0).toUpperCase() }}</div><div class="flex-1 min-w-0"><div class="text-sm font-medium flex items-center gap-2">{{ user.username }}<span v-if="user.username===auth.username" class="text-xs text-gray-500">(bạn)</span><span v-if="isOnline(user)" class="w-2 h-2 rounded-full bg-green-400" title="Online"></span></div><div class="text-xs text-gray-500">{{ user.role }} · {{ formatDate(user.created_at) }} · {{ relative(user.last_active) }}</div></div><button @click="changePassword(user.username)" class="text-xs text-amber-400">Đổi MK</button><button v-if="user.username!==auth.username" @click="remove(user.username)" class="text-xs text-red-400">Xóa</button></article></div></section>
</div></div></template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { createUser, deleteUser, getUsers, updateUserPassword } from '@/api/users'; import { useAuthStore } from '@/stores/auth';
const auth=useAuthStore(),users=ref([]),newUser=reactive({username:'',password:'',role:'user'}),message=ref(''),ok=ref(false); const load=async()=>{users.value=await getUsers()||[];};
const add=async()=>{try{await createUser({...newUser});Object.assign(newUser,{username:'',password:'',role:'user'});message.value='✓ Đã thêm user.';ok.value=true;await load();}catch(e){message.value=e.message;ok.value=false;}};
const remove=async(username)=>{if(confirm(`Xóa user "${username}"?`)){await deleteUser(username);await load();}};
const changePassword=async(username)=>{const password=prompt(`Mật khẩu mới cho ${username} (tối thiểu 6 ký tự):`);if(password){try{await updateUserPassword(username,password);message.value=`✓ Đã đổi mật khẩu cho ${username}.`;ok.value=true;}catch(e){message.value=e.message;ok.value=false;}}};
const formatDate=v=>v?new Date(v).toLocaleDateString('vi-VN'):'—'; const relative=v=>{if(!v)return'Chưa online';const s=(Date.now()-new Date(v).getTime())/1000;return s<60?'vừa xong':s<3600?`${Math.floor(s/60)} phút trước`:s<86400?`${Math.floor(s/3600)} giờ trước`:`${Math.floor(s/86400)} ngày trước`;}; const isOnline=u=>u.last_active&&Date.now()-new Date(u.last_active).getTime()<300000;onMounted(load);
</script><style scoped>.field{@apply px-3.5 py-2.5 rounded-lg bg-gray-700 border border-gray-600 text-sm focus:outline-none focus:border-indigo-500}</style>
